### ISSUE TITLE
Candles and expire time problem

### ISSUE THREAD

**Issue by lac1995** [theshadow76/ExpertOptionApi#2]
Hi, nice work, I'm trying the API, i navigate a bit the code, i'm not able to retrieve candles due to 'ERROR_WRONG_ASSET_MODE' and cannot understand the time requested from expert option for the expire time.
I've done some test using their "data" for the candles but nothing, and setted a random value for the date and the date worked placing orders after. I see that you're working also on Pocket Option API, I appreciate your work. Where are you from?

**Comment by theshadow76** [comment]
@lac1995 hello!
Yes I've been trying to fix that issue for a while, no look what's o ever, but I'll keep trying to do this!!!

I am from chile BTW.

**Comment by lac1995** [comment]
Hi! I will looking into to help, any idea instead about the expire time setting?
